version: "{build}"
image: Visual Studio 2017
skip_tags: true
cache:
  - C:\Users\appveyor\.m2
build_script:
- cmd: >-
    set JAVA_HOME=C:\Program Files\Java\jdk11

    java -version

    mvn --version

    mvn install --batch-mode %MORE_MAVEN_OPTS%
